name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: gem install jekyll bundler
      - run: bundle install
      - run: jekyll build
